{"name": "run a simple test", "status": "failed", "statusDetails": {"message": "AssertionError: 'automationpractice.com' != 'Mercado Libre Argentina'\n- automationpractice.com\n+ Mercado Libre Argentina\n\n", "trace": "  File \"c:\\users\\ezequiel\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\ezequiel\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\tutorial.py\", line 13, in step_impl\n    assert_equal(context.home_page.get_page_title(), \"Mercado Libre Argentina\")\n  File \"c:\\users\\ezequiel\\appdata\\local\\programs\\python\\python36\\lib\\unittest\\case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"c:\\users\\ezequiel\\appdata\\local\\programs\\python\\python36\\lib\\unittest\\case.py\", line 1203, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"c:\\users\\ezequiel\\appdata\\local\\programs\\python\\python36\\lib\\unittest\\case.py\", line 670, in fail\n    raise self.failureException(msg)\n"}, "steps": [{"name": "Given Navego a la p√°gina de \"http://automationpractice.com/index.php\"", "status": "failed", "statusDetails": {"message": "AssertionError: 'automationpractice.com' != 'Mercado Libre Argentina'\n- automationpractice.com\n+ Mercado Libre Argentina\n\n", "trace": "  File \"c:\\users\\ezequiel\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\ezequiel\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\tutorial.py\", line 13, in step_impl\n    assert_equal(context.home_page.get_page_title(), \"Mercado Libre Argentina\")\n  File \"c:\\users\\ezequiel\\appdata\\local\\programs\\python\\python36\\lib\\unittest\\case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"c:\\users\\ezequiel\\appdata\\local\\programs\\python\\python36\\lib\\unittest\\case.py\", line 1203, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"c:\\users\\ezequiel\\appdata\\local\\programs\\python\\python36\\lib\\unittest\\case.py\", line 670, in fail\n    raise self.failureException(msg)\n"}, "start": 1555307983069, "stop": 1555307985526}, {"name": "When we implement a test", "status": "skipped", "start": 1555307985529, "stop": 1555307985529}, {"name": "Then behave will test it for us!", "status": "skipped", "start": 1555307985529, "stop": 1555307985529}], "start": 1555307983068, "stop": 1555307985529, "uuid": "bdb3f485-1d1c-4819-87e5-c1e546547103", "historyId": "d9e346002b63349ad51101a347ad958c", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "showing off behave"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}